module.exports = [
  { key: 'sistema:admin',          module: 'Sistema',    label: 'Administración',   desc: 'Config, usuarios, permisos',          color: 'red'     },
  { key: 'dashboard:ver',          module: 'Dashboard',  label: 'Ver',              desc: 'KPIs y métricas generales',            color: 'blue'    },
  { key: 'inventario:ver',         module: 'Inventario', label: 'Ver',              desc: 'Listar productos y categorías',         color: 'cyan'    },
  { key: 'inventario:editar',      module: 'Inventario', label: 'Editar',           desc: 'Crear y modificar productos',           color: 'cyan'    },
  { key: 'inventario:borrar',      module: 'Inventario', label: 'Borrar',           desc: 'Eliminar productos (irreversible)',      color: 'cyan'    },
  { key: 'inventario:exportar',    module: 'Inventario', label: 'Exportar CSV',     desc: 'Descargar inventario en CSV',           color: 'cyan'    },
  { key: 'inventario:kardex',      module: 'Inventario', label: 'Kardex',           desc: 'Ver movimientos de stock',              color: 'cyan'    },
  { key: 'servicios:ver',          module: 'Servicios',  label: 'Ver',              desc: 'Planes, contratos, órdenes',            color: 'violet'  },
  { key: 'servicios:crear',        module: 'Servicios',  label: 'Crear',            desc: 'Nuevas órdenes de instalación',         color: 'violet'  },
  { key: 'ventas:ver',             module: 'Ventas',     label: 'Ver',              desc: 'Catálogo, órdenes de trabajo, facturas', color: 'blue'    },
  { key: 'ventas:editar',          module: 'Ventas',     label: 'Editar',           desc: 'Crear y modificar catálogo y OT',        color: 'blue'    },
  { key: 'crm:ver',                module: 'CRM',        label: 'Ver',              desc: 'Clientes, suplidores, prospectos',       color: 'emerald' },
  { key: 'crm:crear',              module: 'CRM',        label: 'Crear/Editar',     desc: 'Alta y modificación de clientes',       color: 'emerald' },
  { key: 'crm:borrar',             module: 'CRM',        label: 'Borrar',           desc: 'Eliminar clientes (irreversible)',       color: 'emerald' },
  { key: 'crm:exportar',           module: 'CRM',        label: 'Exportar CSV',     desc: 'Descarga de datos CRM',                 color: 'emerald' },
  { key: 'crm:editar_email',       module: 'CRM',        label: 'Editar Email',     desc: 'Modificar emails de contacto',          color: 'emerald' },
  { key: 'rrhh:ver',               module: 'RRHH',       label: 'Ver',              desc: 'Técnicos y registros de RRHH',          color: 'sky'     },
  { key: 'rrhh:asistencia',        module: 'RRHH',       label: 'Asistencia',       desc: 'Marcar entrada y salida',               color: 'sky'     },
  { key: 'rrhh:config_seguridad',  module: 'RRHH',       label: 'Config Seguridad', desc: 'Configuración avanzada de RRHH',        color: 'sky'     },
  { key: 'reportes:ver',           module: 'Reportes',   label: 'Ver',              desc: 'Módulo de reportes y KPIs',             color: 'amber'   },
  { key: 'reportes:exportar',      module: 'Reportes',   label: 'Exportar',         desc: 'Reportes financieros y operativos',     color: 'amber'   },
  { key: 'mapa:ver',               module: 'Mapa NOC',   label: 'Ver Mapa',         desc: 'Mapa de infraestructura',               color: 'teal'    },
]
