-- Enable Row Level Security on all tables (Supabase compliance)
-- Node.js service role bypasses RLS so app behaviour is unchanged.

ALTER TABLE "Rol" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Empleado" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SessionToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Asistencia" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Categoria" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Producto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MovimientoInventario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Plan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlantillaEquipo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Cliente" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PortalSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Servicio" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrdenInstalacion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DetalleOrden" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Suplidor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Prospecto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ItemCatalogo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrdenTrabajo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LineaOrdenTrabajo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Factura" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LineaFactura" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConfiguracionNCF" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CarritoTemp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LineaCarrito" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_EmpleadoToRol" ENABLE ROW LEVEL SECURITY;
